title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
plugins:
  - jekyll-sitemap

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"


url: https://waxmole.github.io/games/
