title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
permalink: pretty
logo: "/img/logo.svg"
color_scheme: dark
encoding: UTF-8
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
include:
  - js

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"


url: https://waxmole.github.io/games/
